name: Deploy Next App
on: push 
jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Run application eslint
        run: yarn eslint
      - name: Build application
        run: yarn build
      - name: Deploy
        run: echo Deployment...
